// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// words
export const GET_WORDS_SUCCESS = 'GET_WORDS'
export const GET_WORDS_FAIL = 'GET_WORDS'
export const SAVE_WORD_SUCCESS = 'SAVE_WORD_SUCCESS'
export const SAVE_WORD_FAIL = 'SAVE_WORD_FAIL'
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS'
export const UPDATE_WORD_SUCCESS = 'UPDATE_WORD_SUCCESS'

// lists
export const GET_LISTS = 'GET_LISTS'
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS'
export const SAVE_LIST_FAIL = 'SAVE_LIST_FAIL'
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'

// utils
export const TOGGLE_SLIDESCREEN = 'TOGGLE_SLIDESCREEN'
export const GET_SEARCH_TERM = 'GET_SEARCH_TERM'