// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const SIGN_OUT = 'SIGN_OUT'

// words
export const GET_WORDS_SUCCESS = 'GET_WORDS'
export const GET_WORDS_FAIL = 'GET_WORDS'
export const SAVE_WORD_SUCCESS = 'SAVE_WORD_SUCCESS'
export const SAVE_WORD_FAIL = 'SAVE_WORD_FAIL'
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS'
export const UPDATE_WORD_SUCCESS = 'UPDATE_WORD_SUCCESS'

// lists
export const GET_LISTS = 'GET_LISTS'
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS'
export const SAVE_LIST_FAIL = 'SAVE_LIST_FAIL'
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'

// review
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS'
export const GET_EMPTY_REVIEW = 'GET_EMPTY_REVIEW'
export const CORRECT_ANSWER = 'CORRECT_ANSWER'
export const CLEAR_REVIEW = 'CLEAR_REVIEW'
export const GET_NEXT_WORD = 'GET_NEXT_WORD'
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER'

// utils
export const TOGGLE_SLIDESCREEN = 'TOGGLE_SLIDESCREEN'
export const GET_SEARCH_TERM = 'GET_SEARCH_TERM'
export const OPEN_CREATE_LIST = 'OPEN_CREATE_LIST'
export const OPEN_EDIT_LIST = 'OPEN_EDIT_LIST'
export const OPEN_CREATE_WORD = 'OPEN_CREATE_WORD'
export const OPEN_EDIT_WORD = 'OPEN_EDIT_WORD'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

// alerts
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';